<?php
/**
 * @file travisbuilder.module
 * Trigger CI builds within Drupal.
 */

use Travis\Client;

define('TRAVISBUILDER_API_FREE', 'https://api.travis-ci.org');
define('TRAVISBUILDER_API_PAID', 'https://api.travis-ci.com');

/**
 * Implements hook_menu().
 */
function travisbuilder_menu() {
  $path = 'admin/config/system/travisbuilder';

  $items[$path] = array(
    'title' => 'Travis Builder',
    'description' => 'Configure Travis settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('travisbuilder_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'travisbuilder.admin.inc',
  );
  $items[$path . '/default'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items[$path . '/build'] = array(
    'title' => 'Trigger Build',
    'description' => t('Trigger a Travis build via a URL.'),
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('travisbuilder_build_confirm_form'),
    'access arguments' => array('trigger travis builds'),
    'file' => 'travisbuilder.admin.inc',
  );

  $items[$path . '/history'] = array(
    'title' => 'History',
    'description' => t('Recent Travis builds.'),
    'type' => MENU_LOCAL_TASK,
    'page callback' => array('travisbuilder_build_list_page'),
    'weight' => 10,
    'access arguments' => array('administer site configuration'),
    'file' => 'travisbuilder.admin.inc',
  );

  return $items;
}


/**
 * Implements hook_admin_paths().
 */
function travisbuilder_admin_paths() {
  $paths = array(
    'admin/system/travis-builder' => TRUE,
  );
  return $paths;
}


/**
 * Impements hook_permission().
 */
function travisbuilder_permission() {
  return array(
    'trigger travis builds' => array(
      'title' => t('Restart Travis builds'),
      'description' => t('Manually trigger a Travis build restart.'),
    ),
  );
}


/**
 * Mix param(s) and global settings.
 *
 * @return array
 */
function _travisbuilder_configs() {
  // @todo With multiple repos, will need update.
  $configs = array();
  $defaults = array(
    'private' => 0,
    'repo' => '',
    'branch' => 'master',
    'access_token' => '',
    'schedule' => 10800,
  );
  foreach ($defaults as $key => $default) {
    $configs[$key] = variable_get('travisbuilder_' . $key, $default);
  }

  return $configs;
}


/**
 * Wrapper to return a Travis client.
 *
 * @param string $repository
 *   Name of repository.
 *
 * @return \Travis\Client|null
 *   If the module is successfully configured, a fully configured Elomentary
 *   client will be returned. Otherwise, NULL will be returned.
 */
function travisbuilder_client($repository, $clientInterface) {
  $client = &drupal_static(__FUNCTION__, array());

  // Only instantiate a new client if one hasn't already been.
  if (!$client && $repository) {
    // @todo With multiple repos, will need update.
    $configs = _travisbuilder_configs();
    $configs['repo'] = $repository;
    $token = ($configs['access_token']) ? $configs['access_token'] : FALSE;

    // Instantiate Travis client via library.
    try {
      $client = new Client(NULL, $clientInterface, $token);
    }
    catch (FieldException $e) {
      throw new DrupalException("Error using Travis client with message: " . $e->getMessage());
    }

    if ($configs['private']) {
      $client->setApiUrlPrivate();
    }
    if ($client) {
      // Allow other modules to alter the client before it is used / returned.
      drupal_alter('travisbuilder_client', $client);
    }
  }

  return $client;
}


/**
 * Trigger a Travis build to occur on the globally configured repo.
 *
 * @todo Enable reaching farther back (pagination) to always find a build for a branch.
 * Requires use of after_number API element.
 *
 * Resources:
 *   http://docs.travis-ci.com/api/#jobs
 *
 * @param string $repository
 *   Name of repository.
 *
 * @return boolean
 *   Result of build.
 */
function _travisbuilder_trigger_build($repository, $branch = FALSE, $ignore_lifetime = FALSE) {
  $configs = _travisbuilder_configs();
  $branch = $branch ?: $configs['branch'];
  $time_since_last = time() - variable_get('travisbuilder_last', 0);
  $watchdog_link = 'admin/config/system/travisbuilder';
  $result = array(
    'status' => FALSE,
    'vars' => array()
  );

  // Honor minimum lifetime.
  if ($ignore_lifetime || ($time_since_last > $configs['schedule'])) {
    // Get the right build.
    $client = travisbuilder_client($repository, 'Buzz\Client\Curl');
    $repo_client = $client->fetchRepository($repository);
    // Find the right build.
    $builds = $repo_client->getBuilds()->findBy(array('branch' => $branch));
    $build = $builds->first();

    if ($build) {
      // Attempt to trigger.
      $resonse = $client->restartBuild($build, $configs['access_token']);

      // Interpret the response.
      reset($resonse['flash'][0]);
      $result['status'] = (key($resonse['flash'][0]) === 'error') ? FALSE : TRUE;
      $result['message'] = '@message (Build ID: @build)';
      $result['vars'] = array(
        '@message' => current($resonse['flash'][0]),
        '@build' => $build->getId(),
      );
      $build_url = format_string('https://travis-ci.org/!repo/builds/!id', array(
        '!repo' => $repository,
        '!id' => $build->getId(),
      ));
      $watchdog_link = l('Visit Travis build #' . $build->getNumber(), $build_url);

      // Timer for next time.
      variable_set('travisbuilder_last', time());
    }
    else {
      $result['message'] = 'No build can be found for the current configurations.';
    }
  }
  else {
    $result['message'] = 'Build restart failed due to minimum time limit';
  }

  $severity = ($result['status']) ? WATCHDOG_NOTICE : WATCHDOG_ERROR;
  watchdog('travisbuilder', $result['message'], $result['vars'], $severity, $watchdog_link);

  return $result;
}
